const urlBase = `https://marketplace.visualstudio.com/items?itemName=`

export const VsCodeExtensionContent = [
  { id: 1, name: 'Auto Add Brackets in String Interpolation', link: `${urlBase}aliariff.auto-add-brackets`, },
  { id: 2, name: 'Auto Rename Tag', link: `${urlBase}formulahendry.auto-rename-tag`, },
  { id: 3, name: 'Babel JavaScript', link: `${urlBase}mgmcdermott.vscode-language-babel`, },
  { id: 4, name: 'Code Spell Checker', link: `${urlBase}streetsidesoftware.code-spell-checker`, },
  { id: 5, name: 'Code Time', link: `${urlBase}softwaredotcom.swdc-vscode`, },
  { id: 6, name: 'colorize', link: `${urlBase}kamikillerto.vscode-colorize`, },
  { id: 7, name: 'CSS Peek', link: `${urlBase}pranaygp.vscode-css-peek`, },
  { id: 8, name: 'Error Lens', link: `${urlBase}usernamehw.errorlens`, },
  { id: 9, name: 'ES7+ React/Redux/React-Native snippets', link: `${urlBase}dsznajder.es7-react-js-snippets`, },
  { id: 10, name: 'GitLens — Git supercharged', link: `${urlBase}eamodio.gitlens`, },
  { id: 11, name: 'Image preview', link: `${urlBase}kisstkondoros.vscode-gutter-preview`, },
  { id: 12, name: 'Import Cost', link: `${urlBase}wix.vscode-import-cost`, },
  { id: 13, name: 'IntelliCode', link: `${urlBase}VisualStudioExptTeam.vscodeintellicode`, },
  { id: 14, name: 'IntelliCode API Usage Examples', link: `${urlBase}VisualStudioExptTeam.intellicode-api-usage-examples`, },
  { id: 15, name: 'IntelliSense for CSS class names in HTML', link: `${urlBase}Zignd.html-css-class-completion`, },
  { id: 16, name: 'Material Icon Theme', link: `${urlBase}PKief.material-icon-theme`, },
  { id: 17, name: 'Package Json Upgrade', link: `${urlBase}codeandstuff.package-json-upgrade`, },
  { id: 18, name: 'Power Mode', link: `${urlBase}hoovercj.vscode-power-mode`, },
  { id: 19, name: 'Prettier - Code formatter', link: `${urlBase}esbenp.prettier-vscode`, },
  { id: 20, name: 'Project Dashboard', link: `${urlBase}kruemelkatze.vscode-dashboard`, },
  { id: 21, name: 'React/Redux/react-router Snippets', link: `${urlBase}discountry.react-redux-react-router-snippets`, },
  { id: 22, name: 'Regex Previewer', link: `${urlBase}chrmarti.regex`, },
  { id: 23, name: 'SVG', link: `${urlBase}jock.svg`, },
  { id: 24, name: 'Tailwind CSS IntelliSense', link: `${urlBase}bradlc.vscode-tailwindcss`, },
  { id: 25, name: 'VSCode React Refactor', link: `${urlBase}planbcoding.vscode-react-refactor`, },
]
